# Generated by Django 3.2.6 on 2021-08-17 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of publishment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_excerpt',
            field=models.TextField(verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_tittle',
            field=models.CharField(max_length=255, verbose_name='Tittle'),
        ),
    ]
